Create shared python package, use it from both cloud functions and both cloud run services, and clean up duplicate code.
SatcherInstitute/prototype pull request #42
Opened 2020-10-02 13:26 UTC by aaronsn

See README for more detail on the code setup

2020-10-02 16:12 UTC, jenniebrown requested changes
Thanks for figuring this out! It occurs to me that it would be awesome if we could split up the packages with finer granularity so we wouldn't have to import all of the code in each Run service (e.g. upload to GCS code not being installed by the gcs-to-bq pipeline) but maybe that will be easier to do when we get rid of the cloud functions?

2020-10-02 16:12 UTC, jenniebrown commented on .gitignore
> -gcs_to_bq.zip
In general, avoid removing things from the .gitignore. The .gitignore is a shared place that everyone uses and removing files from it risks someone accidentally committing files to the repo that shouldn't be there.

In this case, I think it would make sense to coalesce these .zip files into one *.zip line since I don't forsee us needing to include zip files in the repo

2020-10-02 16:12 UTC, jenniebrown commented on README.md
> +2. Run `cd/<service_directory>`, then `pip-compile requirements.in`. This will generate a `requirements.txt` file.
I think your cd command is missing a space

2020-10-02 16:12 UTC, jenniebrown commented on README.md
> +  - For Cloud Run, you can then set the `run_ingestion_image_path` variable in your tfvars file to `gcr.io/<project-id>/<your-ingestion-image-name>` and `run_gcs_to_bq_image_path` to `gcr.io/<project
nit: I'm lukewarm on the italics at the end of this step.

2020-10-02 16:12 UTC, jenniebrown commented on README.md
>  4. Build and push your Docker images to Google Container Registry. Select any unique identifier for `your-[ingestion|gcs-to-bq]-image-name`.
This isn't part of your change, but while you're here, could you add a newline between the tics and the cd command in the code block in step 3?

2020-10-02 16:12 UTC, jenniebrown commented on python/main.py
> +    logging.error("Could not load json object: %s", err)
I don't think the 'data' field is used anywhere in the code. This block can be deleted.

2020-10-02 19:42 UTC, aaronsn reviewed
> Thanks for figuring this out! It occurs to me that it would be awesome if we could split up the packages with finer granularity so we wouldn't have to import all of the code in each Run service (e.g. upload to GCS code not being installed by the gcs-to-bq pipeline) but maybe that will be easier to do when we get rid of the cloud functions?

Yeah there's definitely room for improvement here, though I'm not sure what the ideal setup is (I've never set up a python project like this before so I'm kind of learning as I go). One way to do it is to have a setup.py function within each sub-folder within python/, and then the Dockerfile for each service gets updated to copy/install just the packages that are being used for that service. I think the bigger concern isn't our code since there won't be a ton of it, but the dependencies they rely on which will be much larger. Eg it's not a big deal if run_ingestion installs our whole ./python package, but it really doesn't need pandas or BQ APIs. For that, we can already accomplish it with the current setup by just having each service's requirements.in file only specify what is needed, but that seems brittle long-term because it's unclear which deps are needed. I think potentially one setup is to use the install_requires option in the setup.py file, but you still want a requirements.txt to specify which version of the deps to use and to ensure sub-packages that have the same deps are compatible. Anyyyyway, I'm gonna paste this all into a github issue to generally figure out the deps story - we should definitely get back to it but I think it's fine to wait until we have a clearer picture of the full project requirements.

2020-10-02 19:42 UTC, aaronsn commented on .gitignore
> -gcs_to_bq.zip
Ah good call. Changed to *.zip

2020-10-02 19:42 UTC, aaronsn commented on python/main.py
> +    logging.error("Could not load json object: %s", err)
Nice

2020-10-02 21:40 UTC, aaronsn commented
Did a little more digging and put a brain dump on build setup into https://github.com/SatcherInstitute/health-equity-tracker/issues/27. My preference is still to submit this as-is so we can get rid of the forked code, and then investigate further as a followup

2020-10-05 18:07 UTC, jenniebrown approved these changes

2020-10-05 18:20 UTC, mayaspivak approved these changes

2020-10-06 16:01 UTC, jenniebrown approved these changes

2020-10-06 16:01 UTC, jenniebrown commented on run_gcs_to_bq/requirements.txt
> +#    pip-compile '.\requirements.in'
Is this slash the wrong way? I think it should be ./

2020-10-06 16:18 UTC, merged